### ISSUE TITLE
Allow specifying an output directory

### ISSUE THREAD

**Issue by aMytho** [alexpado/hoyoverse-music-unpacker#7]
I think it would be useful to extract the files to a specific directory instead of the same directory as the executable.

I did some modifications and managed to get it working. If you think this would be useful, I'll make a PR.

**Comment by alexpado** [comment]
Hi ! 
I'm open to contributions, it's always a pleasure ! :)

If you did the modification based on the `master` branch, this might break upon merging `feature/refactoring` due to a huge amount of edits. 
On that branch, I made it so each game will be extracted in their own folders (`extracted/GAME`), see [Line 42 in GameUnpacker.java](https://github.com/alexpado/hoyoverse-music-unpacker/blob/feature/refactoring/src/main/java/ovh/akio/hmu/GameUnpacker.java#L42)

The idea would be that `GameUnpacker` could accept an optional value setting the base directory, as `asLocalDirectory` can accept a `File` instance as argument to set the root path.

**Comment by aMytho** [comment]
I made the PR #8 

I initially did it on the `master` branch, but I re-wrote it for the new branch.

**Comment by aMytho** [comment]
Merged in #8
